import { createClientFromRequest } from 'npm:@base44/sdk@0.5.0';
import { SendEmail } from '@/integrations/Core';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req).asServiceRole;
    const { org_id, workspace_id, alert_id } = await req.json();
    
    if (!org_id || !alert_id) {
      return Response.json({ error: 'org_id and alert_id are required' }, { status: 400 });
    }
    
    // Get the alert details
    const alerts = await base44.entities.Alert.filter({ id: alert_id });
    if (alerts.length === 0) {
      return Response.json({ error: 'Alert not found' }, { status: 404 });
    }
    
    const alert = alerts[0];
    
    // Get notification channels for this org/workspace
    const channels = await base44.entities.AlertChannel.filter({
      org_id: org_id,
      workspace_id: workspace_id,
      enabled: true
    });
    
    const notificationResults = [];
    
    for (const channel of channels) {
      // Check if this channel should receive notifications for this rule
      if (channel.rule_filters.length > 0 && !channel.rule_filters.includes(alert.rule_name)) {
        continue;
      }
      
      try {
        if (channel.channel_type === 'email') {
          // Send email notifications
          const emailAddresses = channel.config.email_addresses || [];
          for (const email of emailAddresses) {
            const severityColor = alert.severity === 'critical' ? '#dc2626' : '#f59e0b';
            const workspaceDisplay = workspace_id || 'Organization-wide';
            const timeDisplay = new Date(alert.created_date).toLocaleString();
            
            const emailBody = `<h2 style="color: ${severityColor};">${alert.title}</h2>` +
              `<p><strong>Severity:</strong> ${alert.severity.toUpperCase()}</p>` +
              `<p><strong>Workspace:</strong> ${workspaceDisplay}</p>` +
              `<p><strong>Message:</strong> ${alert.message}</p>` +
              `<p><strong>Time:</strong> ${timeDisplay}</p>` +
              `<hr><p><small>This alert was generated by knXw monitoring system.</small></p>`;

            const emailResult = await SendEmail({
              to: email,
              subject: `🚨 ${alert.title}`,
              body: emailBody
            });
            
            notificationResults.push({
              channel_id: channel.id,
              type: 'email',
              target: email,
              success: true,
              details: emailResult
            });
          }
        }
        
        else if (channel.channel_type === 'slack') {
          // Send Slack webhook notification
          const webhookUrl = channel.config.slack_webhook_url;
          if (webhookUrl) {
            const slackPayload = {
              text: `🚨 ${alert.title}`,
              attachments: [
                {
                  color: alert.severity === 'critical' ? 'danger' : 'warning',
                  fields: [
                    {
                      title: 'Severity',
                      value: alert.severity.toUpperCase(),
                      short: true
                    },
                    {
                      title: 'Workspace',
                      value: workspace_id || 'Organization-wide',
                      short: true
                    },
                    {
                      title: 'Message',
                      value: alert.message,
                      short: false
                    },
                    {
                      title: 'Time',
                      value: new Date(alert.created_date).toLocaleString(),
                      short: true
                    }
                  ]
                }
              ]
            };
            
            const slackResponse = await fetch(webhookUrl, {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify(slackPayload)
            });
            
            notificationResults.push({
              channel_id: channel.id,
              type: 'slack',
              target: 'webhook',
              success: slackResponse.ok,
              details: { status: slackResponse.status }
            });
          }
        }
        
        else if (channel.channel_type === 'sms') {
          // SMS notifications would require a service like Twilio
          // For now, we'll just log that SMS notifications are configured
          notificationResults.push({
            channel_id: channel.id,
            type: 'sms',
            target: 'configured',
            success: false,
            details: { message: 'SMS notifications not implemented yet' }
          });
        }
        
      } catch (error) {
        console.error(`Failed to send notification via channel ${channel.id}:`, error);
        notificationResults.push({
          channel_id: channel.id,
          type: channel.channel_type,
          success: false,
          error: error.message
        });
      }
    }
    
    // Update alert to mark notifications as sent
    await base44.entities.Alert.update(alert_id, {
      notification_sent: true
    });
    
    return Response.json({
      success: true,
      alert_id: alert_id,
      channels_processed: channels.length,
      notification_results: notificationResults
    });
    
  } catch (error) {
    console.error('Channel notification failed:', error);
    return Response.json({ 
      error: 'Channel notification failed', 
      details: error.message 
    }, { status: 500 });
  }
});