
/**
 * Production AWS SES email notification system
 * Sends transactional emails for psychographic insights and platform notifications
 */

import { createClientFromRequest } from 'npm:@base44/sdk@0.7.0';
import { SESClient, SendEmailCommand, SendTemplatedEmailCommand } from 'npm:@aws-sdk/client-ses@3.427.0';

const AWS_REGION = Deno.env.get('AWS_REGION') || 'us-east-1';
const FROM_EMAIL = Deno.env.get('SES_FROM_EMAIL') || 'noreply@knxw.app';
const FROM_NAME = Deno.env.get('SES_FROM_NAME') || 'knXw Platform';

/**
 * Initialize SES client with proper configuration
 */
function createSESClient() {
  const config = { region: AWS_REGION };

  const accessKeyId = Deno.env.get('AWS_ACCESS_KEY_ID');
  const secretAccessKey = Deno.env.get('AWS_SECRET_ACCESS_KEY');
  
  if (accessKeyId && secretAccessKey) {
    config.credentials = {
      accessKeyId,
      secretAccessKey,
      sessionToken: Deno.env.get('AWS_SESSION_TOKEN'),
    };
  }

  return new SESClient(config);
}

/**
 * Send psychographic insight notification email
 * @param {string} toEmail - Recipient email address
 * @param {object} insight - Psychographic insight data
 * @param {object} userProfile - Associated user profile
 */
async function sendInsightNotification(toEmail, insight, userProfile) {
  const ses = createSESClient();
  
  const subject = `New ${insight.insight_type.replace('_', ' ')} insight for ${userProfile.user_id}`;
  
  const htmlBody = `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; line-height: 1.6; color: #333; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { background: linear-gradient(135deg, #00d4ff 0%, #0ea5e9 100%); color: white; padding: 30px; text-align: center; border-radius: 8px 8px 0 0; }
        .content { background: #f8f9fa; padding: 30px; border-radius: 0 0 8px 8px; }
        .insight-box { background: white; padding: 20px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #00d4ff; }
        .confidence-bar { background: #e9ecef; height: 8px; border-radius: 4px; margin: 10px 0; }
        .confidence-fill { background: #00d4ff; height: 100%; border-radius: 4px; transition: width 0.3s ease; }
        .recommendations { background: #fff3cd; border: 1px solid #ffeaa7; padding: 15px; border-radius: 8px; margin: 15px 0; }
        .footer { text-align: center; margin-top: 30px; color: #6c757d; font-size: 12px; }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="header">
          <h1>🧠 knXw Psychographic Insight</h1>
          <p>New behavioral pattern detected</p>
        </div>
        
        <div class="content">
          <div class="insight-box">
            <h2>${insight.title}</h2>
            <p><strong>Type:</strong> ${insight.insight_type.replace('_', ' ')}</p>
            <p><strong>Priority:</strong> ${insight.priority}</p>
            
            <div class="confidence-bar">
              <div class="confidence-fill" style="width: ${(insight.confidence_score * 100)}%"></div>
            </div>
            <small>Confidence: ${(insight.confidence_score * 100).toFixed(1)}%</small>
            
            <p>${insight.description}</p>
            
            ${insight.actionable_recommendations?.length > 0 ? `
              <div class="recommendations">
                <h3>💡 Recommended Actions:</h3>
                <ul>
                  ${insight.actionable_recommendations.map(rec => `<li>${rec}</li>`).join('')}
                </ul>
              </div>
            ` : ''}
          </div>
          
          <div style="background: white; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <h3>User Context</h3>
            <p><strong>Risk Profile:</strong> ${userProfile.risk_profile}</p>
            <p><strong>Cognitive Style:</strong> ${userProfile.cognitive_style}</p>
            ${userProfile.emotional_state?.mood ? `<p><strong>Current Mood:</strong> ${userProfile.emotional_state.mood}</p>` : ''}
            ${userProfile.motivation_stack?.length > 0 ? `
              <p><strong>Primary Motivations:</strong> ${userProfile.motivation_stack.slice(0, 3).join(', ')}</p>
            ` : ''}
          </div>
        </div>
        
        <div class="footer">
          <p>This insight was generated by knXw's AI-powered psychographic analysis engine.</p>
          <p>Visit your <a href="https://knxw.app/insights" style="color: #00d4ff;">insights dashboard</a> for more details.</p>
        </div>
      </div>
    </body>
    </html>
  `;
  
  const textBody = `
knXw Psychographic Insight

${insight.title}

Type: ${insight.insight_type.replace('_', ' ')}
Priority: ${insight.priority}
Confidence: ${(insight.confidence_score * 100).toFixed(1)}%

${insight.description}

${insight.actionable_recommendations?.length > 0 ? `
Recommended Actions:
${insight.actionable_recommendations.map(rec => `• ${rec}`).join('\n')}
` : ''}

User Context:
- Risk Profile: ${userProfile.risk_profile}
- Cognitive Style: ${userProfile.cognitive_style}
${userProfile.emotional_state?.mood ? `- Current Mood: ${userProfile.emotional_state.mood}` : ''}
${userProfile.motivation_stack?.length > 0 ? `- Primary Motivations: ${userProfile.motivation_stack.slice(0, 3).join(', ')}` : ''}

Visit https://knxw.app/insights for more details.
  `;

  const command = new SendEmailCommand({
    Source: `${FROM_NAME} <${FROM_EMAIL}>`,
    Destination: {
      ToAddresses: [toEmail]
    },
    Message: {
      Subject: {
        Data: subject,
        Charset: 'UTF-8'
      },
      Body: {
        Html: {
          Data: htmlBody,
          Charset: 'UTF-8'
        },
        Text: {
          Data: textBody,
          Charset: 'UTF-8'
        }
      }
    }
  });

  try {
    const response = await ses.send(command);
    
    console.log(JSON.stringify({
      event: 'ses_insight_notification_sent',
      message_id: response.MessageId,
      to_email: toEmail,
      insight_type: insight.insight_type,
      user_id: userProfile.user_id,
      success: true
    }));

    return {
      success: true,
      messageId: response.MessageId,
      timestamp: new Date().toISOString()
    };
    
  } catch (error) {
    console.error(JSON.stringify({
      event: 'ses_insight_notification_failed',
      to_email: toEmail,
      insight_type: insight.insight_type,
      user_id: userProfile.user_id,
      error: error.message,
      error_code: error.name
    }));
    
    throw error;
  }
}

/**
 * Send weekly psychographic summary email
 * @param {string} toEmail - Recipient email address
 * @param {object} summaryData - Weekly summary statistics and insights
 */
async function sendWeeklySummary(toEmail, summaryData) {
  const ses = createSESClient();
  
  const subject = `Your Weekly Psychographic Intelligence Summary`;
  
  const htmlBody = `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; line-height: 1.6; color: #333; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { background: linear-gradient(135deg, #00d4ff 0%, #0ea5e9 100%); color: white; padding: 30px; text-align: center; border-radius: 8px 8px 0 0; }
        .stat-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 15px; margin: 20px 0; }
        .stat-card { background: white; padding: 20px; border-radius: 8px; text-align: center; border: 1px solid #e9ecef; }
        .stat-number { font-size: 2em; font-weight: bold; color: #00d4ff; }
        .stat-label { color: #6c757d; font-size: 0.9em; }
        .insight-list { background: white; padding: 20px; border-radius: 8px; margin: 15px 0; }
        .insight-item { padding: 10px 0; border-bottom: 1px solid #f1f3f4; }
        .insight-item:last-child { border-bottom: none; }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="header">
          <h1>📊 Weekly Intelligence Report</h1>
          <p>Your psychographic analytics summary for ${summaryData.period}</p>
        </div>
        
        <div style="background: #f8f9fa; padding: 30px; border-radius: 0 0 8px 8px;">
          <div class="stat-grid">
            <div class="stat-card">
              <div class="stat-number">${summaryData.totalProfiles || 0}</div>
              <div class="stat-label">Active Profiles</div>
            </div>
            <div class="stat-card">
              <div class="stat-number">${summaryData.newInsights || 0}</div>
              <div class="stat-label">New Insights</div>
            </div>
            <div class="stat-card">
              <div class="stat-number">${summaryData.totalEvents || 0}</div>
              <div class="stat-label">Events Tracked</div>
            </div>
            <div class="stat-card">
              <div class="stat-number">${summaryData.engagementRate || '0'}%</div>
              <div class="stat-label">Avg Engagement</div>
            </div>
          </div>
          
          ${summaryData.topInsights?.length > 0 ? `
            <div class="insight-list">
              <h3>🎯 Key Insights This Week</h3>
              ${summaryData.topInsights.map(insight => `
                <div class="insight-item">
                  <strong>${insight.title}</strong>
                  <p style="margin: 5px 0; color: #6c757d;">${insight.description}</p>
                  <small style="color: #00d4ff;">Confidence: ${(insight.confidence_score * 100).toFixed(1)}%</small>
                </div>
              `).join('')}
            </div>
          ` : ''}
          
          ${summaryData.recommendations?.length > 0 ? `
            <div style="background: #fff3cd; border: 1px solid #ffeaa7; padding: 15px; border-radius: 8px; margin: 15px 0;">
              <h3>💡 This Week's Recommendations</h3>
              <ul>
                ${summaryData.recommendations.map(rec => `<li>${rec}</li>`).join('')}
              </ul>
            </div>
          ` : ''}
        </div>
        
        <div style="text-align: center; margin-top: 30px; color: #6c757d; font-size: 12px;">
          <p>View your complete analytics at <a href="https://knxw.app/dashboard" style="color: #00d4ff;">knxw.app/dashboard</a></p>
          <p>Generated by knXw AI • ${new Date().toLocaleDateString()}</p>
        </div>
      </div>
    </body>
    </html>
  `;

  const command = new SendEmailCommand({
    Source: `${FROM_NAME} <${FROM_EMAIL}>`,
    Destination: {
      ToAddresses: [toEmail]
    },
    Message: {
      Subject: {
        Data: subject,
        Charset: 'UTF-8'
      },
      Body: {
        Html: {
          Data: htmlBody,
          Charset: 'UTF-8'
        }
      }
    }
  });

  try {
    const response = await ses.send(command);
    
    console.log(JSON.stringify({
      event: 'ses_weekly_summary_sent',
      message_id: response.MessageId,
      to_email: toEmail,
      success: true
    }));

    return {
      success: true,
      messageId: response.MessageId,
      timestamp: new Date().toISOString()
    };
    
  } catch (error) {
    console.error(JSON.stringify({
      event: 'ses_weekly_summary_failed',
      to_email: toEmail,
      error: error.message,
      error_code: error.name
    }));
    
    throw error;
  }
}

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    if (req.method !== 'POST') {
      return Response.json({ error: 'Method not allowed' }, { status: 405 });
    }

    const body = await req.json();
    const { action, data } = body;

    switch (action) {
      case 'send_insight_notification': { // Added block scope
        const { toEmail, insight, userProfile } = data;
        
        if (!toEmail || !insight || !userProfile) {
          return Response.json({ 
            error: 'toEmail, insight, and userProfile are required' 
          }, { status: 400 });
        }

        const result = await sendInsightNotification(toEmail, insight, userProfile);
        
        return Response.json({
          success: true,
          message: 'Insight notification sent successfully',
          data: result
        });
      } // End of block scope

      case 'send_weekly_summary': { // Added block scope
        const { email, summaryData } = data;
        
        if (!email || !summaryData) {
          return Response.json({ 
            error: 'email and summaryData are required' 
          }, { status: 400 });
        }

        const summaryResult = await sendWeeklySummary(email, summaryData);
        
        return Response.json({
          success: true,
          message: 'Weekly summary sent successfully',
          data: summaryResult
        });
      } // End of block scope

      case 'test_connection': { // Added block scope
        // Test SES connectivity by sending a simple test email
        const testCommand = new SendEmailCommand({
          Source: `${FROM_NAME} <${FROM_EMAIL}>`,
          Destination: {
            ToAddresses: [user.email]
          },
          Message: {
            Subject: {
              Data: 'knXw SES Connection Test',
              Charset: 'UTF-8'
            },
            Body: {
              Text: {
                Data: 'This is a test email to verify SES connectivity. If you receive this, the integration is working correctly.',
                Charset: 'UTF-8'
              }
            }
          }
        });

        const ses = createSESClient();
        const response = await ses.send(testCommand);
        
        return Response.json({
          success: true,
          message: 'SES connection test successful',
          data: {
            messageId: response.MessageId,
            fromEmail: FROM_EMAIL,
            region: AWS_REGION
          }
        });
      } // End of block scope

      default:
        return Response.json({ 
          error: `Unknown action: ${action}` 
        }, { status: 400 });
    }

  } catch (error) {
    console.error('SES notification function error:', error);
    
    return Response.json({ 
      error: error.message || 'Internal server error',
      details: error.stack
    }, { status: 500 });
  }
});
