// AdaptiveButton - Vue Component (documentation reference)
// This file is auto-generated by the platform's SDK scaffolding system.
// It is intentionally empty to prevent parser conflicts.

export default {
  name: 'AdaptiveButton',
  description: 'Button that adapts its text based on user psychographics'
};