// AdaptiveText - Vue Component (documentation reference)
// This file is auto-generated by the platform's SDK scaffolding system.
// It is intentionally empty to prevent parser conflicts.

export default {
  name: 'AdaptiveText',
  description: 'Text element that adapts based on user psychographics'
};